#!/usr/bin/env python
# vim: set fileencoding=utf-8 filetype=python:

'''
PURPOSE:
Make readline friendly with tab automcomplete
and save history to file

NOTES:
1. `man python` and search for `PYTHONSTARTUP` variable
2. https://github.com/stroparo/czlinux/blob/7eaab90a10fc28b89f3bb9d13682f10e74381364/conf/pystartup
3. http://docs.python.org/3.3/library/rlcompleter.html
'''

import atexit
import os
import readline
import rlcompleter


# Save startup history path
history_path = os.getenv('PYTHONSTARTUP')

# Read startup history
if os.path.exists(history_path):
    readline.read_history_file(history_path)

# Setup Automcomplete
readline.parse_and_bind('tab: complete')


# Save startup history on python shell exit
atexit.register(readline.write_history_file, history_path)


# Destroy unused variables
del os, atexit, readline, rlcompleter, history_path
